import { Download, FileText, Presentation, Share2 } from 'lucide-react'

const outputs = [
	{
		icon: FileText,
		title: 'CSRD / ESRS E1 packs',
		desc: 'Auto-generated disclosure tables with methodology appendices and evidence links.'
	},
	{
		icon: Presentation,
		title: 'Board presentations',
		desc: 'Executive summaries with trend charts, target progress, and peer benchmarks.'
	},
	{
		icon: Share2,
		title: 'Stakeholder portals',
		desc: 'Read-only views for investors, procurement, and sustainability committees.'
	},
	{
		icon: Download,
		title: 'Auditor exports',
		desc: 'XBRL-ready datasets with full calculation lineage and source document hashes.'
	}
]

/** Future Payload mapping: reportingFeatures. */
export function Reporting() {
	return (
		<section
			id='reporting'
			className='px-5 py-20 [background:color-mix(in_oklch,var(--blue)_4%,var(--ice))] sm:px-8 sm:py-28'
		>
			<div className='mx-auto max-w-6xl'>
				<div className='grid gap-12 lg:grid-cols-2 lg:items-center'>
					<div className='me-reveal'>
						<p className='text-xs uppercase tracking-[0.28em] [color:var(--blue)]'>
							Reporting
						</p>
						<h2 className='mt-3 font-[family-name:var(--font-display)] text-[clamp(2rem,5vw,3rem)] leading-[1.06] [color:var(--ink)]'>
							From raw spend to signed disclosures.
						</h2>
						<p className='mt-4 text-base leading-relaxed [color:var(--mute)]'>
							Measure generates the reports your CFO, CSO, and external auditors
							need — with every number traceable to source transactions.
						</p>
						<div className='mt-8 space-y-4'>
							{outputs.map(o => (
								<div key={o.title} className='flex gap-4'>
									<o.icon
										className='mt-0.5 h-5 w-5 shrink-0 [color:var(--blue)]'
										strokeWidth={1.5}
									/>
									<div>
										<p className='font-medium [color:var(--ink)]'>{o.title}</p>
										<p className='mt-1 text-sm leading-relaxed [color:var(--mute)]'>
											{o.desc}
										</p>
									</div>
								</div>
							))}
						</div>
					</div>

					<div className='me-reveal overflow-hidden rounded-sm border border-[var(--line)]'>
						{/* biome-ignore lint/performance/noImgElement: concept preview placeholder */}
						<img
							src='https://picsum.photos/seed/measure-report/640/480'
							alt='Sample ESG board report generated by Measure'
							className='h-full w-full object-cover'
						/>
					</div>
				</div>
			</div>
		</section>
	)
}
